# 데이터 변경

In [1]:
#필요 라이브러리 로딩
import numpy as np
import pandas as pd

In [2]:
#지난 시간에 저장한 csv 로딩

df = pd.read_csv('./stuedent.csv')
display(df)

    이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [3]:
import os

os.getcwd() #현재 디랙토리 위치

'C:\\Users\\jaeha'

### 컬럼 생성

In [4]:
# '등급' 컬럼 생성
df['등급'] = 'A' #새로운 컬럼 명시 후 값 부여
display(df)

    이름   학과   성적 등급
0  아이유  국문학  3.0  A
1  김연아   수학  1.0  A
2  홍길동  컴퓨터  3.5  A
3  장범준   철학  2.7  A
4  강감찬  경영학  4.0  A

In [5]:
# 성적에 따라 등급부여
grade = np.array(['B', 'D', 'B', 'C', 'A'])
df['등급'] = grade
display(df)

    이름   학과   성적 등급
0  아이유  국문학  3.0  B
1  김연아   수학  1.0  D
2  홍길동  컴퓨터  3.5  B
3  장범준   철학  2.7  C
4  강감찬  경영학  4.0  A

In [6]:
# 나이를 의미하는 age 라는 시리즈 생성

age = pd.Series([21, 20, 24, 23, 28])

df['나이'] = age
display(df)

    이름   학과   성적 등급  나이
0  아이유  국문학  3.0  B  21
1  김연아   수학  1.0  D  20
2  홍길동  컴퓨터  3.5  B  24
3  장범준   철학  2.7  C  23
4  강감찬  경영학  4.0  A  28

### 인덱스 설정 및 리셋

In [7]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
# 데이터 프레임의 인덱스는 df.index를 명시하여 접근할 수 있음
df.index = ["one", "two", "three", "four", "five"] # 인덱스의 값을 바꾸고 싶다면 인데스의 개수 만큼의 원소를 포함한 리스트를 할당하여 변경
df

        이름   학과   성적 등급  나이
one    아이유  국문학  3.0  B  21
two    김연아   수학  1.0  D  20
three  홍길동  컴퓨터  3.5  B  24
four   장범준   철학  2.7  C  23
five   강감찬  경영학  4.0  A  28

In [9]:
# 새로운 컬럼 성별[sex] 생성
sex = pd.Series(['여자', '여자','남자', '남자', '님자'])
df['성별'] = sex
display(df)

        이름   학과   성적 등급  나이   성별
one    아이유  국문학  3.0  B  21  NaN
two    김연아   수학  1.0  D  20  NaN
three  홍길동  컴퓨터  3.5  B  24  NaN
four   장범준   철학  2.7  C  23  NaN
five   강감찬  경영학  4.0  A  28  NaN

In [10]:
# sex 시리즈 인덱스 확인
sex.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
# 시리즈 sex와 데이터프레임 df의 인덱스 출력
print('시리즈 sex의 인덱스 -->', sex.index)
print('데이터프레임 df의 인덱스 -->', df.index)

시리즈 sex의 인덱스 --> RangeIndex(start=0, stop=5, step=1)
데이터프레임 df의 인덱스 --> Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [12]:
#인덱스 통일 후 다시 성별 컬럼에 값 부여
sex.index = df.index
df['성별'] = sex
display(df)

        이름   학과   성적 등급  나이  성별
one    아이유  국문학  3.0  B  21  여자
two    김연아   수학  1.0  D  20  여자
three  홍길동  컴퓨터  3.5  B  24  남자
four   장범준   철학  2.7  C  23  남자
five   강감찬  경영학  4.0  A  28  님자

In [13]:
#현재 설정되어 있는 인덱스 리셋
#df.reset_index(inplace=True) # inplace = True라는 인수값을 주면 원본에 바로 적용
df.reset_index()

   index   이름   학과   성적 등급  나이  성별
0    one  아이유  국문학  3.0  B  21  여자
1    two  김연아   수학  1.0  D  20  여자
2  three  홍길동  컴퓨터  3.5  B  24  남자
3   four  장범준   철학  2.7  C  23  남자
4   five  강감찬  경영학  4.0  A  28  님자

In [14]:
df

        이름   학과   성적 등급  나이  성별
one    아이유  국문학  3.0  B  21  여자
two    김연아   수학  1.0  D  20  여자
three  홍길동  컴퓨터  3.5  B  24  남자
four   장범준   철학  2.7  C  23  남자
five   강감찬  경영학  4.0  A  28  님자

In [15]:
df.reset_index(inplace=True)
df

   index   이름   학과   성적 등급  나이  성별
0    one  아이유  국문학  3.0  B  21  여자
1    two  김연아   수학  1.0  D  20  여자
2  three  홍길동  컴퓨터  3.5  B  24  남자
3   four  장범준   철학  2.7  C  23  남자
4   five  강감찬  경영학  4.0  A  28  님자

In [16]:
#index 설정
#df.set_index('index', inplace=True) index 컬럼에 대하여 set_index
df.set_index('이름')

     index   학과   성적 등급  나이  성별
이름
아이유    one  국문학  3.0  B  21  여자
김연아    two   수학  1.0  D  20  여자
홍길동  three  컴퓨터  3.5  B  24  남자
장범준   four   철학  2.7  C  23  남자
강감찬   five  경영학  4.0  A  28  님자

In [17]:
#원본에 적용
df.set_index('index', inplace=True)

In [18]:
display(df)

        이름   학과   성적 등급  나이  성별
index
one    아이유  국문학  3.0  B  21  여자
two    김연아   수학  1.0  D  20  여자
three  홍길동  컴퓨터  3.5  B  24  남자
four   장범준   철학  2.7  C  23  남자
five   강감찬  경영학  4.0  A  28  님자

### 컬럼 삭제

In [19]:
# 성별 컬럼 삭제 (dataframe의 drop 메서드 이용)
df.drop('성별', axis=1) #drop에서 axis=1의 값을 주면 컬럼을 삭제하겠다는 의미

        이름   학과   성적 등급  나이
index
one    아이유  국문학  3.0  B  21
two    김연아   수학  1.0  D  20
three  홍길동  컴퓨터  3.5  B  24
four   장범준   철학  2.7  C  23
five   강감찬  경영학  4.0  A  28

In [20]:
df

        이름   학과   성적 등급  나이  성별
index
one    아이유  국문학  3.0  B  21  여자
two    김연아   수학  1.0  D  20  여자
three  홍길동  컴퓨터  3.5  B  24  남자
four   장범준   철학  2.7  C  23  남자
five   강감찬  경영학  4.0  A  28  님자

In [23]:
df.drop('성별', axis='columns') #axis = 1 대신 axis='colsums' 라고 직접 명시해주어도 됨

        이름   학과   성적 등급  나이
index
one    아이유  국문학  3.0  B  21
two    김연아   수학  1.0  D  20
three  홍길동  컴퓨터  3.5  B  24
four   장범준   철학  2.7  C  23
five   강감찬  경영학  4.0  A  28

In [24]:
df #원본 dataframe에선 성별 컬럼이 삭제되지 안흥ㄴ걸을 확인

        이름   학과   성적 등급  나이  성별
index
one    아이유  국문학  3.0  B  21  여자
two    김연아   수학  1.0  D  20  여자
three  홍길동  컴퓨터  3.5  B  24  남자
four   장범준   철학  2.7  C  23  남자
five   강감찬  경영학  4.0  A  28  님자

In [26]:
#컬럼을 완전히 삭제 하는 방법

#방법1. 해당 피처를 제외한 새로운 데이터프레임 생성
df2 = df.drop('성별', axis=1)
df2

        이름   학과   성적 등급  나이
index
one    아이유  국문학  3.0  B  21
two    김연아   수학  1.0  D  20
three  홍길동  컴퓨터  3.5  B  24
four   장범준   철학  2.7  C  23
five   강감찬  경영학  4.0  A  28

In [27]:
# 원본 데이터 변경 확인
df

        이름   학과   성적 등급  나이  성별
index
one    아이유  국문학  3.0  B  21  여자
two    김연아   수학  1.0  D  20  여자
three  홍길동  컴퓨터  3.5  B  24  남자
four   장범준   철학  2.7  C  23  남자
five   강감찬  경영학  4.0  A  28  님자

In [28]:
#방법2. 원본데이터에서 해당 피처 삭제
df.drop('성별', axis=1, inplace=True) # inplace=True 인수 설정

In [30]:
df

        이름   학과   성적 등급  나이
index
one    아이유  국문학  3.0  B  21
two    김연아   수학  1.0  D  20
three  홍길동  컴퓨터  3.5  B  24
four   장범준   철학  2.7  C  23
five   강감찬  경영학  4.0  A  28

In [31]:
# 데이터 프레임 행 삭제
df.drop('one', axis=0) #one이라는 인덱스를 가진 행을 삭제

        이름   학과   성적 등급  나이
index
two    김연아   수학  1.0  D  20
three  홍길동  컴퓨터  3.5  B  24
four   장범준   철학  2.7  C  23
five   강감찬  경영학  4.0  A  28

# 실습: 전국 무인 단속 카메라 표준데이터 json 데이터 pandas로 호출하기

In [1]:
#필요 라이브러리 로딩
import pandas as pd
import json #json을 다루기 위한 라이브러리
import requests #서버 쪽에 request 보낼 때 사용하는 라이브러리

In [9]:
# open api 호출시 필요한 정보 입력

key = 'RYTXXdeEW3GPhSUZ1Cs3uf4Dal3DY6eRbkPmlloN4aUwD4EMrAYNPBKjI1flxNpYeicFg9a53ZCIC%2F5sjbqTFQ%3D%3D'

pageNo = 0 # 요청 변수 : 페이지 번호 입력
row = 100 # 요청 변수 : 한페이지 결과 수 입력

# full url 입력 : '주소' + '?servicekey=키' + &pageNo=페이지번호'+'&numOfRows= 한 페이지 출력 괄과수' + '&type=json'
url = f'http://api.data.go.kr/openapi/tn_pubr_public_unmanned_traffic_camera_api?serviceKey={key}&pageNo={pageNo}&numOfRows={row}&type=json'

response = requests.get(url)

# 한글 출력 시 encoding이 필요함
response.encoding = 'utf-8' #utf-8으로 설정

print(response.text[0:600]) # response객체의 text 출력(출력되는 글자수를 지정함)

{"response":{"header":{"resultCode":"00","resultMsg":"NORMAL_SERVICE","type":"json"},"body":{"items":[{"mnlssRegltCameraManageNo":"23","ctprvnNm":"전라북도","signguNm":"익산시","roadKnd":"기타","roadRouteNo":"","roadRouteNm":"동서로","roadRouteDrc":"3","rdnmadr":"","lnmadr":"전라북도 익산시 남중동 375-193","latitude":"35.9533199","longitude":"126.9589814","itlpc":"남중동 북부시장사거리","regltSe":"4","lmttVe":"0","regltSctnLcSe":"","ovrspdRegltSctnLt":"","prtcareaType":"","installationYear":"2015","institutionNm":"전라북도 익산시청","phoneNumber":"063-859-5571","referenceDate":"2023-09-04","insttCode":"4680000"},{"mnlssRegltCameraMa

In [12]:
# 2. 결과 객체에 있는 데이터(json)조회
resulting_dict = json.loads(response.text) #json을 dict 타입으로 바꾸는 함수
#print(resulting_dict['header'])
resulting_dict.keys() # dictionary 키 확인 --> 중첩 딕셔너리임

dict_keys(['response'])

In [13]:
#중첩 딕셔너리 키확인
resulting_dict['response'].keys()

dict_keys(['header', 'body'])

In [14]:
resulting_dict['response']['body'].keys()

dict_keys(['items', 'totalCount', 'numOfRows', 'pageNo'])

In [15]:
resulting_dict['response']['body']['items']

[{'mnlssRegltCameraManageNo': '23',
  'ctprvnNm': '전라북도',
  'signguNm': '익산시',
  'roadKnd': '기타',
  'roadRouteNo': '',
  'roadRouteNm': '동서로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '전라북도 익산시 남중동 375-193',
  'latitude': '35.9533199',
  'longitude': '126.9589814',
  'itlpc': '남중동 북부시장사거리',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2015',
  'institutionNm': '전라북도 익산시청',
  'phoneNumber': '063-859-5571',
  'referenceDate': '2023-09-04',
  'insttCode': '4680000'},
 {'mnlssRegltCameraManageNo': '24',
  'ctprvnNm': '전라북도',
  'signguNm': '익산시',
  'roadKnd': '기타',
  'roadRouteNo': '',
  'roadRouteNm': '고봉로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '전라북도 익산시 영등동 867',
  'latitude': '35.9603375',
  'longitude': '126.9712455',
  'itlpc': '영등2동 아이스링크',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2013',
  'institutionNm': '전라북도 익산시청',
  'phoneNumber': '063-859-5571',
  'referenceDate': '2023-09-04',
  'insttCode': '4680000'},
 {'mnlssRegltCameraManageNo': '25',
  'ctprvnNm': '전라북도',
  'signguNm': '익산시',
  'roadKnd': '기타',
  'roadRouteNo': '',
  'roadRouteNm': '무왕로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '전라북도 익산시 어양동 663',
  'latitude': '35.9620134',
  'longitude': '126.9812617',
  'itlpc': '영등1동 전자랜드사거리',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2013',
  'institutionNm': '전라북도 익산시청',
  'phoneNumber': '063-859-5571',
  'referenceDate': '2023-09-04',
  'insttCode': '4680000'},
 {'mnlssRegltCameraManageNo': '26',
  'ctprvnNm': '전라북도',
  'signguNm': '익산시',
  'roadKnd': '기타',
  'roadRouteNo': '',
  'roadRouteNm': '선화로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '전라북도 익산시 모현동1가 915',
  'latitude': '35.9508394',
  'longitude': '126.9378014',
  'itlpc': '모현동 부영1차아파트',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2016',
  'institutionNm': '전라북도 익산시청',
  'phoneNumber': '063-859-5571',
  'referenceDate': '2023-09-04',
  'insttCode': '4680000'},
 {'mnlssRegltCameraManageNo': '27',
  'ctprvnNm': '전라북도',
  'signguNm': '익산시',
  'roadKnd': '기타',
  'roadRouteNo': '',
  'roadRouteNm': '인북로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '전라북도 익산시 영등동 543-56',
  'latitude': '35.9472724',
  'longitude': '126.9641853',
  'itlpc': '영등1동 동부시장',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2015',
  'institutionNm': '전라북도 익산시청',
  'phoneNumber': '063-859-5571',
  'referenceDate': '2023-09-04',
  'insttCode': '4680000'},
 {'mnlssRegltCameraManageNo': '28',
  'ctprvnNm': '전라북도',
  'signguNm': '익산시',
  'roadKnd': '기타',
  'roadRouteNo': '',
  'roadRouteNm': '인북로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '전라북도 익산시 남중동 375-193',
  'latitude': '35.9533199',
  'longitude': '126.9589814',
  'itlpc': '남중동 북부시장',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2015',
  'institutionNm': '전라북도 익산시청',
  'phoneNumber': '063-859-5571',
  'referenceDate': '2023-09-04',
  'insttCode': '4680000'},
 {'mnlssRegltCameraManageNo': '29',
  'ctprvnNm': '전라북도',
  'signguNm': '익산시',
  'roadKnd': '기타',
  'roadRouteNo': '',
  'roadRouteNm': '중앙로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '전라북도 익산시 중앙동1가 87',
  'latitude': '35.94003024',
  'longitude': '126.9489387',
  'itlpc': '중앙동 중앙시장길 앞',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2015',
  'institutionNm': '전라북도 익산시청',
  'phoneNumber': '063-859-5571',
  'referenceDate': '2023-09-04',
  'insttCode': '4680000'},
 {'mnlssRegltCameraManageNo': '30',
  'ctprvnNm': '전라북도',
  'signguNm': '익산시',
  'roadKnd': '기타',
  'roadRouteNo': '',
  'roadRouteNm': '평동로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '전라북도 익산시 동산동 685',
  'latitude': '35.9296355',
  'longitude': '126.9575522',
  'itlpc': '동산동 E마트',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2015',
  'institutionNm': '전라북도 익산시청',
  'phoneNumber': '063-859-5571',
  'referenceDate': '2023-09-04',
  'insttCode': '4680000'},
 {'mnlssRegltCameraManageNo': '31',
  'ctprvnNm': '전라북도',
  'signguNm': '익산시',
  'roadKnd': '기타',
  'roadRouteNo': '',
  'roadRouteNm': '무왕로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '전라북도 익산시 영등동 869',
  'latitude': '35.9601511',
  'longitude': '126.9748498',
  'itlpc': '영등2동 롯데마트',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2015',
  'institutionNm': '전라북도 익산시청',
  'phoneNumber': '063-859-5571',
  'referenceDate': '2023-09-04',
  'insttCode': '4680000'},
 {'mnlssRegltCameraManageNo': '7',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '구도',
  'roadRouteNo': '',
  'roadRouteNm': '송화로',
  'roadRouteDrc': '2',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 화평동 1-48',
  'latitude': '37.4803298',
  'longitude': '126.6328919',
  'itlpc': '송화로 송현초교 앞',
  'regltSe': '1',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '2',
  'installationYear': '2018',
  'institutionNm': '인천지방경찰청',
  'phoneNumber': '032-455-2352',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '8',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '구도',
  'roadRouteNo': '',
  'roadRouteNm': '화도진로',
  'roadRouteDrc': '2',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송림동 253-2',
  'latitude': '37.4741829',
  'longitude': '126.6360756',
  'itlpc': '화도진로 송림초교 앞',
  'regltSe': '01+02',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '2',
  'installationYear': '2018',
  'institutionNm': '인천지방경찰청',
  'phoneNumber': '032-455-2352',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '9',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '구도',
  'roadRouteNo': '',
  'roadRouteNm': '화도진로',
  'roadRouteDrc': '1',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송림동 253-2',
  'latitude': '37.4740801',
  'longitude': '126.6361129',
  'itlpc': '화도진로 송림초교 건너편',
  'regltSe': '01+02',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '2',
  'installationYear': '2018',
  'institutionNm': '인천지방경찰청',
  'phoneNumber': '032-455-2352',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '10',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '구도',
  'roadRouteNo': '',
  'roadRouteNm': '샛골로',
  'roadRouteDrc': '2',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송림동 39',
  'latitude': '37.4794202',
  'longitude': '126.6453835',
  'itlpc': '샛골로 서흥초교 앞',
  'regltSe': '01+02',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '2',
  'installationYear': '2018',
  'institutionNm': '인천지방경찰청',
  'phoneNumber': '032-455-2352',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '11',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '구도',
  'roadRouteNo': '',
  'roadRouteNm': '샛골로',
  'roadRouteDrc': '1',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송림동 39',
  'latitude': '37.47907874',
  'longitude': '126.6452356',
  'itlpc': '샛골로 서흥초교 건너편',
  'regltSe': '01+02',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '2',
  'installationYear': '2018',
  'institutionNm': '인천지방경찰청',
  'phoneNumber': '032-455-2352',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '12',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '구도',
  'roadRouteNo': '',
  'roadRouteNm': '화수로',
  'roadRouteDrc': '2',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 화수동 4-33',
  'latitude': '37.4842011',
  'longitude': '126.6315697',
  'itlpc': '화도진중학교 앞',
  'regltSe': '01+02',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '2',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '13',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '구도',
  'roadRouteNo': '',
  'roadRouteNm': '화수로',
  'roadRouteDrc': '1',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 화수동 4-33',
  'latitude': '37.483979',
  'longitude': '126.6318021',
  'itlpc': '화도진중학교 건너편',
  'regltSe': '01+02',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '99',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '14',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '인중로',
  'roadRouteDrc': '1',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 만석동 2-328',
  'latitude': '37.4869664',
  'longitude': '126.6215253',
  'itlpc': '만석부두입구 사거리',
  'regltSe': '01+02',
  'lmttVe': '50',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '99',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '15',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '인중로',
  'roadRouteDrc': '2',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 만석동 5-5',
  'latitude': '37.4869735',
  'longitude': '126.6220581',
  'itlpc': '만석부두입구 사거리',
  'regltSe': '01+02',
  'lmttVe': '50',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '99',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '16',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '새천년로',
  'roadRouteDrc': '2',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송림동 45-23',
  'latitude': '37.4745187',
  'longitude': '126.6486282',
  'itlpc': '송림3.5동 행정복지센터 앞',
  'regltSe': '01+02',
  'lmttVe': '50',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '99',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '17',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '새천년로',
  'roadRouteDrc': '1',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송림동 96',
  'latitude': '37.4741254',
  'longitude': '126.648787',
  'itlpc': '동산중·고등학교 정류장 앞',
  'regltSe': '01+02',
  'lmttVe': '50',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '99',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '18',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '동산로',
  'roadRouteDrc': '1',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송림동 39',
  'latitude': '37.47269034',
  'longitude': '126.6474024',
  'itlpc': '동산중학교 앞',
  'regltSe': '01+02',
  'lmttVe': '50',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '99',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '19',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '동산로',
  'roadRouteDrc': '2',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송림동 39',
  'latitude': '37.47303671',
  'longitude': '126.6472284',
  'itlpc': '동산중학교 건너편',
  'regltSe': '01+02',
  'lmttVe': '50',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '99',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '20',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '송림로',
  'roadRouteDrc': '2',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송림동 39',
  'latitude': '37.47578759',
  'longitude': '126.6444118',
  'itlpc': '송림오거리',
  'regltSe': '01+02',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '2',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '21',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '송현로',
  'roadRouteDrc': '2',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송현동 159',
  'latitude': '37.4799464',
  'longitude': '126.6368297',
  'itlpc': '송현동주공1차 정문 앞',
  'regltSe': '01+02',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '2',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '22',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '송현로',
  'roadRouteDrc': '1',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송현동 55-1',
  'latitude': '37.47980706',
  'longitude': '126.6365495',
  'itlpc': '송현동주공1차 정문 건너편',
  'regltSe': '01+02',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '2',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '23',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '인중로',
  'roadRouteDrc': '1',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 화수동 7-454',
  'latitude': '37.4858991',
  'longitude': '126.630121',
  'itlpc': '화수사거리',
  'regltSe': '01+02',
  'lmttVe': '50',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '99',
  'installationYear': '2019',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '24',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '송림로',
  'roadRouteDrc': '1',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송림동 235-3',
  'latitude': '37.47379568',
  'longitude': '126.6382487',
  'itlpc': '송림초교 후문',
  'regltSe': '01+02',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '2',
  'installationYear': '2020',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': '25',
  'ctprvnNm': '인천광역시',
  'signguNm': '동구',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '송림로',
  'roadRouteDrc': '2',
  'rdnmadr': '',
  'lnmadr': '인천광역시 동구 송림동 210-24',
  'latitude': '37.4738489',
  'longitude': '126.638694',
  'itlpc': '송림초교 후문 맞은편',
  'regltSe': '01+02',
  'lmttVe': '30',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '2',
  'installationYear': '2020',
  'institutionNm': '인천광역시 동구청',
  'phoneNumber': '032-770-6595',
  'referenceDate': '2023-10-20',
  'insttCode': '3500000'},
 {'mnlssRegltCameraManageNo': 'P-7706',
  'ctprvnNm': '경기도',
  'signguNm': '고양시',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '호수로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '경기도 고양시 일산서구 대화동 2602',
  'latitude': '37.66799365',
  'longitude': '126.7516307',
  'itlpc': '대화동 2602 현대백화점 정문',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2014',
  'institutionNm': '경기도 고양시',
  'phoneNumber': '031-8075-2578',
  'referenceDate': '2023-09-22',
  'insttCode': '3940000'},
 {'mnlssRegltCameraManageNo': 'P-7707',
  'ctprvnNm': '경기도',
  'signguNm': '고양시',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '호수로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '경기도 고양시 일산서구 대화동 2602-2',
  'latitude': '37.66718203',
  'longitude': '126.7510935',
  'itlpc': '대화동 2602-2 현대백화점 후문',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2014',
  'institutionNm': '경기도 고양시',
  'phoneNumber': '031-8075-2578',
  'referenceDate': '2023-09-22',
  'insttCode': '3940000'},
 {'mnlssRegltCameraManageNo': 'P-7708',
  'ctprvnNm': '경기도',
  'signguNm': '고양시',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '주엽로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '경기도 고양시 일산서구 대화동 1050-171',
  'latitude': '37.66727315',
  'longitude': '126.7536584',
  'itlpc': '대화동 1050-171 빅마켓 정문',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2014',
  'institutionNm': '경기도 고양시',
  'phoneNumber': '031-8075-2578',
  'referenceDate': '2023-09-22',
  'insttCode': '3940000'},
 {'mnlssRegltCameraManageNo': 'P-7709',
  'ctprvnNm': '경기도',
  'signguNm': '고양시',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '주엽로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '경기도 고양시 일산서구 대화동 1050-171',
  'latitude': '37.667203',
  'longitude': '126.7536584',
  'itlpc': '대화동 1050-171 빅마켓 후문',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2014',
  'institutionNm': '경기도 고양시',
  'phoneNumber': '031-8075-2578',
  'referenceDate': '2023-09-22',
  'insttCode': '3940000'},
 {'mnlssRegltCameraManageNo': 'P-7710',
  'ctprvnNm': '경기도',
  'signguNm': '고양시',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '일산로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '경기도 고양시 일산서구 대화동 2219-2',
  'latitude': '37.67614509',
  'longitude': '126.7461437',
  'itlpc': '대화동 2219-2 신세계오피스텔',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2015',
  'institutionNm': '경기도 고양시',
  'phoneNumber': '031-8075-2578',
  'referenceDate': '2023-09-22',
  'insttCode': '3940000'},
 {'mnlssRegltCameraManageNo': 'P-7711',
  'ctprvnNm': '경기도',
  'signguNm': '고양시',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '일산로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '경기도 고양시 일산서구 대화동 2238',
  'latitude': '37.67447522',
  'longitude': '126.7481578',
  'itlpc': '대화동 2238 노인복지회관(대화동 2515번지 노인복지회관앞 불법주정차 단속용)',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2015',
  'institutionNm': '경기도 고양시',
  'phoneNumber': '031-8075-2578',
  'referenceDate': '2023-09-22',
  'insttCode': '3940000'},
 {'mnlssRegltCameraManageNo': 'P-7712',
  'ctprvnNm': '경기도',
  'signguNm': '고양시',
  'roadKnd': '시도',
  'roadRouteNo': '',
  'roadRouteNm': '주화로',
  'roadRouteDrc': '3',
  'rdnmadr': '',
  'lnmadr': '경기도 고양시 일산서구 대화동 2502',
  'latitude': '37.67626111',
  'longitude': '126.7477259',
  'itlpc': '대화동 2502 백병원 앞',
  'regltSe': '4',
  'lmttVe': '0',
  'regltSctnLcSe': '',
  'ovrspdRegltSctnLt': '',
  'prtcareaType': '',
  'installationYear': '2006',
  'institutionNm': '경기도 고양시',
  'phoneNumber': '031-8075-2578',
  'referenceDate': '2023-09-22',
  'insttCode': '3940000'},
 {'mnlssRegltCameraManageNo': 'P-7713',
  'ctprvnNm': '경기도',
  'signguNm': '고양시',
  'roadKnd': '시도',

In [16]:
#첫번째 아이템 호출
resulting_dict['response']['body']['items'][0]

{'mnlssRegltCameraManageNo': '23',
 'ctprvnNm': '전라북도',
 'signguNm': '익산시',
 'roadKnd': '기타',
 'roadRouteNo': '',
 'roadRouteNm': '동서로',
 'roadRouteDrc': '3',
 'rdnmadr': '',
 'lnmadr': '전라북도 익산시 남중동 375-193',
 'latitude': '35.9533199',
 'longitude': '126.9589814',
 'itlpc': '남중동 북부시장사거리',
 'regltSe': '4',
 'lmttVe': '0',
 'regltSctnLcSe': '',
 'ovrspdRegltSctnLt': '',
 'prtcareaType': '',
 'installationYear': '2015',
 'institutionNm': '전라북도 익산시청',
 'phoneNumber': '063-859-5571',
 'referenceDate': '2023-09-04',
 'insttCode': '4680000'}

In [21]:
# 주소, 카메라 위치, 위도, 경도의 정보만 출력
address_list= []
location_list = []
latitude_list= []
longitude_list =[]

#dictionary 속 데이터 정보 입력

for tmp in resulting_dict['response']['body']['items']:
    address_list.append(tmp['lnmadr'])
    location_list.append(tmp['itlpc'])
    latitude_list.append(tmp['latitude'])
    longitude_list.append(tmp['longitude'])

In [22]:
print(address_list[:10])
print(location_list[:10])
print(longitude_list[:10])

['전라북도 익산시 남중동 375-193', '전라북도 익산시 영등동 867', '전라북도 익산시 어양동 663', '전라북도 익산시 모현동1가 915', '전라북도 익산시 영등동 543-56', '전라북도 익산시 남중동 375-193', '전라북도 익산시 중앙동1가 87', '전라북도 익산시 동산동 685', '전라북도 익산시 영등동 869', '인천광역시 동구 화평동 1-48']
['남중동 북부시장사거리', '영등2동 아이스링크', '영등1동 전자랜드사거리', '모현동 부영1차아파트', '영등1동 동부시장', '남중동 북부시장', '중앙동 중앙시장길 앞', '동산동 E마트', '영등2동 롯데마트', '송화로 송현초교 앞']
['126.9589814', '126.9712455', '126.9812617', '126.9378014', '126.9641853', '126.9589814', '126.9489387', '126.9575522', '126.9748498', '126.6328919']

In [23]:
#dataFrame으로 변환

df = pd.DataFrame({
    'address' : address_list,
    'location' : location_list,
    'latitude' : latitude_list,
    'longitude' : longitude_list
})

display(df)

,address,location,latitude,longitude
0,전라북도 익산시 남중동 375-193,남중동 북부시장사거리,35.9533199,126.9589814
1,전라북도 익산시 영등동 867,영등2동 아이스링크,35.9603375,126.9712455
2,전라북도 익산시 어양동 663,영등1동 전자랜드사거리,35.9620134,126.9812617
3,전라북도 익산시 모현동1가 915,모현동 부영1차아파트,35.9508394,126.9378014
4,전라북도 익산시 영등동 543-56,영등1동 동부시장,35.9472724,126.9641853
...,...,...,...,...
95,경기도 고양시 일산서구 주엽동 101,주엽동 101 강선14단지,37.66848587,126.7620854
96,경기도 고양시 일산서구 주엽동 75,주엽동 75 일산아카데미 앞,37.66781012,126.76666
97,경기도 고양시 일산서구 주엽동 73,주엽동 73 태영프라자 앞,37.66834954,126.765681
98,경기도 고양시 일산서구 주엽동 65,주엽동 65 주엽지구대 앞,37.67037914,126.7645758
99,경기도 고양시 일산서구 주엽동 86,주엽동 86 (강선16단지 앞/강선마을13단지출입구일원),37.66634901,126.765318